myob:
  build: .
  ports:
    - "80:80"
  volumes:
    - ./start.sh:/opt/myob/start.sh
    - ./public:/opt/myob/public
    - ./app.js:/opt/myob/app.js
    - ./tax/rate.json:/opt/myob/public/rate.json
